imports:
- path: db-template.py

resources:
- name: gcpmamie-db
  type: db-template.py
  properties:
    zone: europe-west1-b
    minDbIndex: 0
    maxDbIndex: 1000
    dbName: ssd_prod
    username: ssd_pg
    password: password_en_clair_pas_bien
